### ISSUE TITLE
string.Split() is too abused

### ISSUE THREAD

**Issue by Milkitic** [Naxesss/MapsetParser#7]
Very great modding tool framework so I'm intereted in reading source code. When I focused this I found the parser framework has a mainly problem: the parser is abusing "string.Split()". It's a good choice to save the array result as a varible rather than do multiple same split operations. (one split per line is basis, and for exterme performace we can only use streamreader without split)

**Comment by Naxesss** [comment]
significantly reduced usage of String.Split() in https://github.com/Naxesss/MapsetParser/commit/f938b36460415b3c78c9f25b788a2e55f2bedf15
now splits new lines once and commas once (I think)

may look into streamreader later, but from what I can tell the main issues with performance rn lies in star rating and bezier slider calcs so will probably focus on those first
